#!/usr/bin/env bash
# agent-wt.sh — per-agent git worktree manager.
#
# The problem this solves: many agent sessions (separate Claude Code instances,
# headless/cron jobs) share one repo on one box. They share ONE working tree,
# so one agent's uncommitted edits are visible to — and clobberable by — every
# other agent, and a build/deploy from that tree sweeps up half-finished work.
# guard-edit.sh blocks edits in the main checkout; this script is the positive
# path it points at: one isolated worktree + branch per agent, with a runnable,
# collision-free environment (a per-worktree PORT + state dir) derived per
# worktree.
#
# Worktrees live OUTSIDE the repo ($HOME/.worktrees/<repo>/<slug>) so they are
# never scanned by the build, matched by a deploy glob, or nested in the shared
# tree. The shared .git keeps them cheap — no re-clone.
#
# Portable bash: macOS + Linux. No flock (absent on macOS); locking is
# mkdir-based with a pid-liveness check. Requires: git, awk, sed.
#
#   scripts/agent-wt.sh new <branch> [base]   create/attach a worktree + env
#   scripts/agent-wt.sh ls                     list worktrees + slot + status
#   scripts/agent-wt.sh path <branch|slug>     print a worktree's path
#   scripts/agent-wt.sh rm <branch|slug> [-f]  remove a worktree, free its slot
#   scripts/agent-wt.sh gc                      prune worktrees whose dir is gone
#
# Slot is a stable 0..63 index per worktree. The generated .env derives PORT =
# 8800 + slot; add your service's own per-worktree vars (DB, Redis, ...) in the
# marked block of write_env(), derived from $slot to stay collision-free.

set -uo pipefail

MAX_SLOT=63
PORT_BASE=8800

die() { echo "agent-wt: $*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git not found"

# --- repo + worktree root (resolve from anywhere, incl. inside a worktree) ----
GIT_COMMON_DIR=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) \
    || die "not inside a git repository"
MAIN_REPO=$(dirname "$GIT_COMMON_DIR")
REPO_NAME=$(basename "$MAIN_REPO")
WT_ROOT="${WT_ROOT_BASE:-$HOME/.worktrees}/$REPO_NAME"
REGISTRY="$WT_ROOT/.registry"      # TSV: slug \t slot \t branch \t path
LOCKDIR="$WT_ROOT/.lock"

mkdir -p "$WT_ROOT"
[ -f "$REGISTRY" ] || : > "$REGISTRY"

# --- mkdir-based lock (atomic + portable), with liveness-based recovery -------
acquire_lock() {
    local tries=0 holder
    while ! mkdir "$LOCKDIR" 2>/dev/null; do
        tries=$((tries + 1))
        # Break the lock ONLY if its holder process is gone (a stale lock left
        # by a killed run) — never on a timer, which would kill a live but slow
        # holder. kill -0 is portable (macOS + Linux). An empty/absent pid file
        # means the holder just won the mkdir and hasn't stamped it yet: wait.
        holder=$(cat "$LOCKDIR/pid" 2>/dev/null || true)
        if [ -n "$holder" ] && ! kill -0 "$holder" 2>/dev/null; then
            rm -rf "$LOCKDIR" 2>/dev/null || true
        fi
        [ "$tries" -gt 300 ] && \
            die "could not acquire registry lock ($LOCKDIR); holder pid ${holder:-unknown} still alive"
        sleep 0.1
    done
    echo "$$" > "$LOCKDIR/pid"
    trap 'rm -rf "$LOCKDIR" 2>/dev/null || true' EXIT
}
release_lock() { rm -rf "$LOCKDIR" 2>/dev/null || true; trap - EXIT; }

# --- helpers -----------------------------------------------------------------
# slug: branch name made filesystem- and registry-safe (foo/BAR-1 -> foo-bar-1)
to_slug() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9]+#-#g; s#^-+|-+$##g'; }

registry_field() { # registry_field <slug> <col 1..4>  -> value or empty
    awk -F'\t' -v s="$1" -v c="$2" '$1==s {print $c; exit}' "$REGISTRY"
}

# Resolve a user-supplied "branch or slug" to its registry slug.
resolve_slug() {
    local key slug
    key="$1"; slug=$(to_slug "$key")
    if awk -F'\t' -v s="$slug" '$1==s {found=1} END{exit !found}' "$REGISTRY"; then
        echo "$slug"; return 0
    fi
    # maybe they passed a branch whose slug differs
    awk -F'\t' -v b="$key" '$3==b {print $1; exit}' "$REGISTRY"
}

lowest_free_slot() {
    local used s
    used=$(cut -f2 "$REGISTRY" | sort -n)
    for s in $(seq 0 "$MAX_SLOT"); do
        echo "$used" | grep -qx "$s" || { echo "$s"; return 0; }
    done
    die "no free worktree slot (max $((MAX_SLOT + 1)) concurrent worktrees)"
}

# --- per-worktree env file ---------------------------------------------------
write_env() { # write_env <worktree-dir> <slot> <slug>
    local dir="$1" slot="$2" slug="$3" port state
    port=$((PORT_BASE + slot))
    state="$dir/.worktree-state"
    mkdir -p "$state"
    # .env is gitignored (.env.*) so it never rides a commit out of the worktree.
    cat > "$dir/.env" <<EOF
# Generated by scripts/agent-wt.sh for worktree '$slug' (slot $slot).
# Derived to be collision-free with every other worktree on this box.
# Regenerate with: scripts/agent-wt.sh new <branch>
SERVICE_NAME=$REPO_NAME-wt-$slug
PORT=$port
# Namespaces docker compose resources if this repo uses them:
COMPOSE_PROJECT_NAME=$REPO_NAME-$slug
# Per-worktree state so two agents never share runtime files:
STATE_DIR=$state
# --- service-specific overrides ---------------------------------------------
# Add per-worktree env your service needs, derived from the slot ($slot) so it
# stays collision-free across agents on this box. For example:
#   REDIS_PORT=$((6400 + slot))
#   DATABASE_URL=postgres://localhost/${REPO_NAME}_dev_$slug
EOF
}

# --- subcommands -------------------------------------------------------------
cmd_new() {
    local branch="${1:-}" base="${2:-development}"
    [ -n "$branch" ] || die "usage: agent-wt.sh new <branch> [base]"
    local slug; slug=$(to_slug "$branch")
    [ -n "$slug" ] || die "branch '$branch' produced an empty slug"

    acquire_lock
    local existing_branch existing_path
    existing_branch=$(registry_field "$slug" 3)
    existing_path=$(registry_field "$slug" 4)
    if [ -n "$existing_path" ] && [ -d "$existing_path" ]; then
        if [ "$existing_branch" != "$branch" ]; then
            release_lock
            die "slug '$slug' already maps to branch '$existing_branch' — pick a name that doesn't normalize to the same slug"
        fi
        release_lock
        echo "$existing_path"        # idempotent: reuse, print path for `cd "$(...)"`
        echo "agent-wt: worktree '$slug' already exists — reusing." >&2
        return 0
    fi
    # A row exists but its dir is gone (removed without `gc`): drop it before
    # allocating, so we never append a duplicate row / leak its slot.
    if [ -n "$existing_path" ]; then
        awk -F'\t' -v s="$slug" '$1!=s' "$REGISTRY" > "$REGISTRY.tmp" && mv "$REGISTRY.tmp" "$REGISTRY"
    fi

    local slot; slot=$(lowest_free_slot)
    local dir="$WT_ROOT/$slug"

    # Create the branch off base if it doesn't exist yet; otherwise attach it.
    local add_args=()
    if git show-ref --verify --quiet "refs/heads/$branch"; then
        add_args=("$dir" "$branch")
    else
        add_args=("$dir" -b "$branch" "$base")
    fi
    if ! git -C "$MAIN_REPO" worktree add "${add_args[@]}" >&2; then
        release_lock; die "git worktree add failed"
    fi

    printf '%s\t%s\t%s\t%s\n' "$slug" "$slot" "$branch" "$dir" >> "$REGISTRY"
    release_lock

    write_env "$dir" "$slot" "$slug"
    echo "$dir"
    {
        echo "agent-wt: created worktree '$slug' (slot $slot)"
        echo "  branch : $branch"
        echo "  path   : $dir"
        echo "  PORT   : $((PORT_BASE + slot))"
        echo "  next   : cd \"$dir\"   # then make run"
    } >&2
}

cmd_ls() {
    [ -s "$REGISTRY" ] || { echo "no worktrees"; return 0; }
    printf '%-24s %-5s %-34s %s\n' SLUG SLOT BRANCH STATUS
    while IFS=$'\t' read -r slug slot branch dir; do
        local status
        if [ ! -d "$dir" ]; then status="MISSING (run: gc)"
        elif [ -n "$(git -C "$dir" status --porcelain 2>/dev/null)" ]; then status="dirty"
        else status="clean"; fi
        printf '%-24s %-5s %-34s %s\n' "$slug" "$slot" "$branch" "$status"
    done < "$REGISTRY"
}

cmd_path() {
    local slug; slug=$(resolve_slug "${1:?usage: agent-wt.sh path <branch|slug>}")
    [ -n "$slug" ] || die "no worktree matching '$1'"
    registry_field "$slug" 4
}

cmd_rm() {
    local key="${1:-}" force="${2:-}"
    [ -n "$key" ] || die "usage: agent-wt.sh rm <branch|slug> [-f]"
    local slug; slug=$(resolve_slug "$key")
    [ -n "$slug" ] || die "no worktree matching '$key'"
    acquire_lock
    local dir; dir=$(registry_field "$slug" 4)
    if [ -n "$dir" ] && [ -d "$dir" ]; then
        local rm_args=(worktree remove "$dir")
        [ "$force" = "-f" ] || [ "$force" = "--force" ] && rm_args+=(--force)
        git -C "$MAIN_REPO" "${rm_args[@]}" >&2 || {
            release_lock; die "git worktree remove failed (uncommitted changes? use -f)"; }
    fi
    # drop the registry row (awk: portable, no grep -P)
    awk -F'\t' -v s="$slug" '$1!=s' "$REGISTRY" > "$REGISTRY.tmp"
    mv "$REGISTRY.tmp" "$REGISTRY"
    release_lock
    echo "agent-wt: removed worktree '$slug' (slot freed)" >&2
}

cmd_gc() {
    acquire_lock
    git -C "$MAIN_REPO" worktree prune >&2
    : > "$REGISTRY.tmp"
    local removed=0
    while IFS=$'\t' read -r slug slot branch dir; do
        if [ -d "$dir" ]; then
            printf '%s\t%s\t%s\t%s\n' "$slug" "$slot" "$branch" "$dir" >> "$REGISTRY.tmp"
        else
            removed=$((removed + 1))
        fi
    done < "$REGISTRY"
    mv "$REGISTRY.tmp" "$REGISTRY"
    release_lock
    echo "agent-wt: gc complete ($removed stale entr$([ "$removed" = 1 ] && echo y || echo ies) pruned)" >&2
}

case "${1:-}" in
    new)  shift; cmd_new "$@" ;;
    ls|list) cmd_ls ;;
    path) shift; cmd_path "$@" ;;
    rm|remove) shift; cmd_rm "$@" ;;
    gc|prune) cmd_gc ;;
    ""|help|-h|--help)
        sed -n '2,33p' "$0" | sed 's/^# \{0,1\}//' ;;
    *) die "unknown subcommand '$1' (try: new|ls|path|rm|gc)" ;;
esac
